[package]
name = "fundamentals"
version = "0.1.0"
authors = ["rd3v <blackscreen405@yahoo.co.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
